# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CloudKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CloudKit

    pod 'MJRefresh', '~> 3.1.15.3'
end

target 'UserData' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for CloudKit
    
    pod 'FMDB', '~> 2.7.2'
end
